name: Repo

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [closed]
    branches:
      - 'master'

env:
  PYTHON_VERSION: '3.9'
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - run: echo "Triggered by ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Variables
        run: env

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: 'x64'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Uncomment and adjust the following lines if you want to run tests.
      # - name: Run Unit Tests
      #   run: python -m pytest tests/unit

      # - name: Run Integration Tests
      #   run: python -m pytest tests/integration

      - name: Update script permissions
        run: chmod +x ${{ github.workspace }}/scripts/package.sh

      - name: Zip and Deploy
        run: bash ${{ github.workspace }}/scripts/package.sh deploy checkTickers
